import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/recycling_center.dart';

class RecyclingCenterService {
  // This service returns real recycling center data
  
  Future<List<RecyclingCenter>> getNearbyRecyclingCenters() async {
    // Simulate network delay
    await Future.delayed(const Duration(seconds: 1));
    
    // Return real recycling center data
    return _getRealRecyclingCenters();
  }
  
  List<RecyclingCenter> _getRealRecyclingCenters() {
    return [
      RecyclingCenter(
        id: '1',
        name: 'Ash Recyclers',
        address: 'No. 94, Thimmaiah Road, Bangalore - 01',
        // Using approximate coordinates for Bangalore
        latitude: 12.9716,
        longitude: 77.5946,
        description: 'E-waste recycling facility specializing in electronic waste management.',
        acceptedMaterials: ['Electronics', 'E-waste'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '2',
        name: 'E-Parisara Pvt Ltd',
        address: 'No 30-P3 Dabaspet Bangalore',
        latitude: 12.9716,
        longitude: 77.6050,
        description: 'E-waste recycling center with comprehensive electronic waste management solutions.',
        acceptedMaterials: ['Electronics', 'E-waste', 'Batteries'],
        operatingHours: 'Mon-Sat: 8AM-6PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '3',
        name: 'Eco-Ewaste Recyclers India Pvt Ltd',
        address: 'No.41/1, 42/2, 19 & 20, 2nd Cross, Mutachari Industrial Estate, Hanumanthappa Layout, Mysore Road, Bangalore-560039',
        latitude: 12.9456,
        longitude: 77.5846,
        description: 'E-waste dismantling facility focused on proper disposal and recycling of electronic components.',
        acceptedMaterials: ['Electronics', 'E-waste', 'Computer Parts'],
        operatingHours: 'Mon-Fri: 9AM-6PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '4',
        name: 'Sriram Eco Raksha Computer Services Pvt Ltd',
        address: 'No. B-29, KSSIDC Indl. Estate, Bommasandra, Hosur Road, Anekal Taluk, Bangalore – 560 099',
        latitude: 12.8156,
        longitude: 77.6946,
        description: 'E-waste dismantler specializing in computer and electronic equipment recycling.',
        acceptedMaterials: ['Electronics', 'Computers', 'E-waste'],
        operatingHours: 'Mon-Sat: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '5',
        name: 'E-Ward & Co.',
        address: 'No.6/1B, 14th Cross, Hosur Road, Bommanahalli, Bangalore – 560 068',
        latitude: 12.8956,
        longitude: 77.6246,
        description: 'E-waste recycling center with focus on sustainable electronic waste management.',
        acceptedMaterials: ['Electronics', 'E-waste', 'Batteries'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '6',
        name: 'K.G. Nandini Enterprises',
        address: 'No.46/4, 46/5, Billakempanahalli village, Bidadi Hobli, Ramanagaram District',
        latitude: 12.7816,
        longitude: 77.4246,
        description: 'E-waste recycling facility serving Ramanagaram District and surrounding areas.',
        acceptedMaterials: ['Electronics', 'E-waste'],
        operatingHours: 'Mon-Sat: 8AM-6PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '7',
        name: 'Eco Bird Recycling Company Pvt. Ltd.',
        address: 'No. 185, Azeez Sait Industrial Area, Nayandahalli, Mysore Road, Bangalore – 39',
        latitude: 12.9516,
        longitude: 77.5346,
        description: 'E-waste recycling company with comprehensive electronic waste management solutions.',
        acceptedMaterials: ['Electronics', 'E-waste', 'Batteries'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '8',
        name: 'FA Enterprises',
        address: 'No. B-08, KIADB Industrial Area, Tamaka, Kolar Dist',
        latitude: 13.1356,
        longitude: 78.1246,
        description: 'E-waste recycling center serving Kolar District with electronic waste management services.',
        acceptedMaterials: ['Electronics', 'E-waste'],
        operatingHours: 'Mon-Sat: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '9',
        name: 'Ameena Enterprises',
        address: 'Shed No.C-199, KSSIDC Industrial Estate Hebbal, Mysore – 570 017',
        latitude: 12.3516,
        longitude: 76.6046,
        description: 'E-waste recycling facility located in Mysore providing electronic waste management services.',
        acceptedMaterials: ['Electronics', 'E-waste'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '10',
        name: 'E-R3 Solutions Pvt. Ltd',
        address: 'No.C-430, 1st Cross, 1st Stage Peenya Industrial Area, Bangalore – 560 058',
        latitude: 13.0316,
        longitude: 77.5146,
        description: 'E-waste recycling solutions provider with focus on sustainable electronic waste management.',
        acceptedMaterials: ['Electronics', 'E-waste', 'Batteries'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '11',
        name: 'Trishyirya Recycling India Pvt. Ltd',
        address: 'No.315, 4th Phase, Peenya Industrial Estate, Bangalore – 560 058',
        latitude: 13.0316,
        longitude: 77.5246,
        description: 'E-waste recycling company providing comprehensive electronic waste management services.',
        acceptedMaterials: ['Electronics', 'E-waste'],
        operatingHours: 'Mon-Sat: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '12',
        name: 'E-friendly Waste Recyclers',
        address: 'First Floor, No.17, 1st cross, Azeez Sait Industrial Town, Nayandahalli, Bangalore-560039',
        latitude: 12.9516,
        longitude: 77.5346,
        description: 'E-waste dismantler focused on environmentally friendly electronic waste management.',
        acceptedMaterials: ['Electronics', 'E-waste', 'Computer Parts'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '13',
        name: 'Tech Logic, Unit-2',
        address: 'Shed No.36, 2nd Main, Ranganathapura, Bangalore – 560 044',
        latitude: 12.9716,
        longitude: 77.5646,
        description: 'E-waste recycling center specializing in technology equipment recycling.',
        acceptedMaterials: ['Electronics', 'E-waste', 'Computer Parts'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '14',
        name: 'Samarthanam Trust for the Disabled',
        address: 'No. 66, 6th main, 3rd Phase, Peenya Industrial Area, Bangalore – 560 058',
        latitude: 13.0316,
        longitude: 77.5346,
        description: 'E-waste recycling center operated by a trust that also provides employment opportunities for disabled individuals.',
        acceptedMaterials: ['Electronics', 'E-waste'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '15',
        name: 'Sai Recyclers',
        address: 'No. 20, KSSIDC Industrial Estate, Bhashettihalli, Versandara Post, Doddaballpura Town & Taluk, Bangalore Rural District',
        latitude: 13.2916,
        longitude: 77.5346,
        description: 'E-waste recycling facility serving Bangalore Rural District with electronic waste management services.',
        acceptedMaterials: ['Electronics', 'E-waste'],
        operatingHours: 'Mon-Sat: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
      RecyclingCenter(
        id: '16',
        name: 'Nobel Technology',
        address: 'No.46, 14th Cross, 4th Phase, Peenya Industrial Area, Bangalore - 596 058',
        latitude: 13.0316,
        longitude: 77.5446,
        description: 'E-waste recycling center specializing in technology and electronic equipment recycling.',
        acceptedMaterials: ['Electronics', 'E-waste', 'Computer Parts'],
        operatingHours: 'Mon-Fri: 9AM-5PM',
        contactNumber: '+91-80-XXXXXXXX',
      ),
    ];
  }
  
  // Keeping the original dummy data method for reference or fallback
  List<RecyclingCenter> _getDummyRecyclingCenters() {
    return [
      RecyclingCenter(
        id: '1',
        name: 'Green Earth Recycling',
        address: '123 Eco Street, Green City',
        latitude: 37.7749,
        longitude: -122.4194,
        description: 'A comprehensive recycling facility accepting all types of plastics and paper products.',
        acceptedMaterials: ['PET', 'HDPE', 'LDPE', 'PP', 'PS', 'Paper', 'Glass'],
        operatingHours: 'Mon-Fri: 8AM-6PM, Sat: 9AM-4PM',
        contactNumber: '(555) 123-4567',
      ),
      RecyclingCenter(
        id: '2',
        name: 'City Waste Management',
        address: '456 Recycle Avenue, Green City',
        latitude: 37.7833,
        longitude: -122.4167,
        description: 'Municipal recycling center with drop-off and pick-up services.',
        acceptedMaterials: ['PET', 'HDPE', 'Paper', 'Glass', 'Metal'],
        operatingHours: 'Mon-Sat: 7AM-7PM',
        contactNumber: '(555) 987-6543',
      ),
      RecyclingCenter(
        id: '3',
        name: 'EcoFriendly Solutions',
        address: '789 Sustainability Road, Green City',
        latitude: 37.7694,
        longitude: -122.4862,
        description: 'Specializes in hard-to-recycle materials and electronics.',
        acceptedMaterials: ['Electronics', 'Batteries', 'PET', 'HDPE', 'PP'],
        operatingHours: 'Tue-Sun: 10AM-5PM',
        contactNumber: '(555) 456-7890',
      ),
      RecyclingCenter(
        id: '4',
        name: 'Community Recycling Hub',
        address: '101 Green Lane, Green City',
        latitude: 37.7575,
        longitude: -122.4376,
        description: 'Community-run recycling center with educational programs.',
        acceptedMaterials: ['PET', 'HDPE', 'Paper', 'Organic Waste'],
        operatingHours: 'Wed-Sun: 9AM-3PM',
        contactNumber: '(555) 234-5678',
      ),
      RecyclingCenter(
        id: '5',
        name: 'Industrial Recycling Plant',
        address: '202 Factory Blvd, Green City',
        latitude: 37.7900,
        longitude: -122.4000,
        description: 'Large-scale industrial recycling facility for commercial waste.',
        acceptedMaterials: ['PET', 'HDPE', 'LDPE', 'PP', 'PS', 'Industrial Plastics'],
        operatingHours: 'Mon-Fri: 6AM-8PM',
        contactNumber: '(555) 876-5432',
      ),
    ];
  }
}